seed: 0
device: 0
experiment_name: lego-benchmark
model: 
  n_components: 100_000
  init_random: True
  init_first_frame: False
  init_downsample_factor: null
  dof: 1
  scale: ${model.n_components}
data: 
  model_name: lego
  data_path: ../../data/blender/${data.model_name}
  subsample_factor: null
train: 
  batch_size: 100_000
  learning_rate: 1.0
  beta: 0.0
  n_iters: 1
  top_m: 32
  candidate_m: 128
  densify: False
  densify_point_ratio: 0.0
  densify_unseen_distance_threshold: null
  densify_min_unseen_fraction: 0.0
  densify_min_unseen_points: 0
  densify_reassign_if_full: False
  reassign_fraction: 0.05
  save_every: null
  precision: fp64
output_root: ${oc.env:VBGS_OUTPUT_DIR,../output}
run_name: ${experiment_name}
hydra: 
  job: 
    chdir: True
  run: 
    dir: ${output_root}/${run_name}
  sweep: 
    dir: ${output_root}/sweep/${run_name}
    subdir: ""
